version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: your-backend-app
    ports:
      - '6000:6000'
    environment:
      NODE_ENV: development

